"""Initial schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-01-30 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('path_rule', sa.String(length=200), nullable=True),
    sa.Column('max_capacity', sa.BigInteger(), nullable=True),
    sa.Column('used_capacity', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_engines_is_active'), 'storage_engines', ['is_active'], unique=False)
    
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_filename', sa.String(length=500), nullable=True),
    sa.Column('storage_engine_id', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('upload_ip', sa.String(length=45), nullable=True),
    sa.Column('original_url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['storage_engine_id'], ['storage_engines.id'], )
    )
    op.create_index(op.f('ix_images_storage_engine_id'), 'images', ['storage_engine_id'], unique=False)
    op.create_index(op.f('ix_images_is_deleted'), 'images', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_config_key', 'system_config', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_config_key', table_name='system_config')
    op.drop_table('system_config')
    
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    op.drop_index(op.f('ix_images_is_deleted'), table_name='images')
    op.drop_index(op.f('ix_images_storage_engine_id'), table_name='images')
    op.drop_table('images')
    
    op.drop_index(op.f('ix_storage_engines_is_active'), table_name='storage_engines')
    op.drop_table('storage_engines')
    # ### end Alembic commands ###
